# Generated by Django 3.2 on 2021-05-04 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0004_auto_20210504_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturadet',
            options={'permissions': [('sup_caja_facturadet', 'Permisos de Supervisor de Caja Encabezado')], 'verbose_name': 'Detalle Factura', 'verbose_name_plural': 'Detalles Facturas'},
        ),
    ]
