# Generated by Django 3.2 on 2021-05-04 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0005_alter_facturadet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturadet',
            options={'permissions': [('sup_caja_facturadet', 'Permisos de Supervisor de Caja Detalle')], 'verbose_name': 'Detalle Factura', 'verbose_name_plural': 'Detalles Facturas'},
        ),
    ]
