# Generated by Django 3.2 on 2021-04-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0002_comprasdet_comprasenc'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprasenc',
            name='subtotal_iva',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='comprasenc',
            name='total_iva',
            field=models.FloatField(default=0),
        ),
    ]
